{
    "name": "Attachment Url",
    "summary": """Use attachment URL and upload data to external storage""",
    "category": "Tools",
    "images": [],
    "version": "13.0.2.0.0",
    "application": False,
    "author": "IT-Projects LLC, Ildar Nasyrov",
    "website": "https://apps.odoo.com/apps/modules/12.0/ir_attachment_url/",
    "license": "Other OSI approved licence",  # MIT
    "price": 30.00,
    "currency": "EUR",
    "depends": ["web"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
