{
    "name": "Attachment Url",
    "summary": """Use attachment URL and upload data to external storage""",
    "category": "Tools",
    "images": [],
    "version": "12.0.1.1.12",
    "application": False,
    "author": "IT-Projects LLC, Ildar Nasyrov",
    "website": "https://apps.odoo.com/apps/modules/12.0/ir_attachment_url/",
    "license": "Other OSI approved licence",  # MIT
    "depends": ["web", "product"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "data/ir_attachment_url_data.xml",
        "views/ir_attachment_url_template.xml",
        "views/ir_attachment_res_config.xml",
        "demo/ir_attachment.xml",
    ],
    "qweb": ["static/src/xml/ir_attachment_url.xml"],
    "demo": [],
    "post_load": "post_load",
    "pre_init_hook": None,
    "post_init_hook": None,
    "auto_install": False,
    "installable": True,
}
