{
    "name": "Skype field in partner form",
    "version": "1.0.1",
    "author": "IT-Projects LLC, Ivan Yelizariev",
    "license": "LGPL-3",
    "category": "Tools",
    "website": "https://twitter.com/yelizariev",
    "price": 9.00,
    "currency": "EUR",
    "depends": ["web"],
    "images": ["images/partner.png"],
    "data": ["views.xml", "data.xml"],
    "qweb": ["static/src/xml/base.xml"],
    "installable": True,
}
