{
    "name": """Corsa DRM Major Units""",
    "summary": """The base module for managing major units""",
    "category": "Sales",
    "images": [],
    "version": "11.0.1.1.0",
    "application": False,

    "author": "IT-Projects LLC, Ivan Yelizariev",
    "website": "https://it-projects.info",
    "license": "OPL-1",
    # "price": 9.00,
    # "currency": "EUR",

    "depends": [
        'l10n_us',
        'stock',
        'product_details',
        'drm_product_attributes',
        'sale_margin',
        'part',
        'sale_order_lot_selection',
        'crm',
        'sale_crm',
        'website_sale',
        'web_preview',
        'hr_rule_input_compute',
        'account_invoicing',
        'purchase',
        'multi_attachment_product_image',
    ],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        'data/ir_sequence_data.xml',
        'security/major_unit_security.xml',
        'data/account_data.xml',
        'data/product_data.xml',
        'data/stock_data.xml',
        'data/hr_payroll_data.xml',
        'wizard/service_apply_standard_job_views.xml',
        'wizard/sale_make_invoice_advance_views.xml',
        'views/major_unit_views.xml',
        'views/product_views.xml',
        'views/standard_job_views.xml',
        'views/recall_job_views.xml',
        'views/repair_order_views.xml',
        'views/stock_move_views.xml',
        'views/product_fitment_views.xml',
        'views/sale_views.xml',
        # 'views/sale_deal_views.xml',
        'views/crm_lead_views.xml',
        'views/hr_payroll_views.xml',
        'views/sale_margin_views.xml',
        'views/account_views.xml',
        'security/ir.model.access.csv',
    ],
    "qweb": [
    ],
    "demo": [
        'data/product_demo.xml',
        'data/stock_demo.xml',
        'data/hr_payroll_demo.xml',
        'data/major_unit_demo.xml',
    ],

    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": "post_init_hook",

    "auto_install": False,
    "installable": True,
}
