{
    "name": "Task Search Custom",
    "summary": """Searching for tasks includes "Messages" and "Description" fields""",
    "author": "IT-Projects LLC, Ilmir Karamov",
    "license": "MIT",
    "website": "https://it-projects.info",
    "vesion": "12.0.1.1.0",
    "price": 15.00,
    "currency": "EUR",
    "category": "Project",
    "images": ["images/task_search.png"],
    "depends": ["project"],
    "data": ["views/project_task_search_custom.xml"],
    "installable": False,
}
